[package]
name = "rustc_macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# tidy-alphabetical-start
proc-macro2 = "1"
quote = "1"
regex = "1.3.3"
syn = { version = "2.0.9", features = ["full"] }
synstructure = "0.13.0"
# tidy-alphabetical-end
